ossf/security-insights

examples/security-insights-minimal-sample.yml
examples/security-insights-sample.yml.yml
security-insights-schema-1.0.0.yaml

Enforcing `security-insights-schema-1.0.0.yaml`:
- if `threat-model-created` is true, then `evidence-url` is required
- if `accepts-vulnerability-reports` is true, then `email-contact` and `security-policy` are required

Enforcing schema requirements

---

examples/security-insights-minimal-sample.yml
security-insights-schema-1.0.0.yaml

Enforcing `security-insights-schema-1.0.0.yaml`:
- if `stage` or `bug-fixes-ony` are true, then `core-maintainers` is required

Require maintainers contacts under certain conditions

---

examples/security-insights-sample.yml
security-insights-schema-1.0.0.yaml

This PR adds the properties `in-scope`, `in-scope-comment`, `out-scope`, and `out-scope-comment` in the YAML file. The `in-scope` and `out-scope` vulnerability taxonomy is based on OWASP TOP 10 2021. It could not match every In Scope and/or Out of Scope list, for this reason there is also the voice `other`.

Add in-scope and out-scope properties in vulnerability-reporting property

---

examples/security-insights-sample.yml
security-insights-schema-1.0.0.yaml

Added support to SBOM standards. Users can add links to SBOM files directly in the `SECURITY-INSIGHTS.yml`.

Add support to SBOM standards

---

examples/security-insights-minimal-sample.yml
examples/security-insights-sample.yml
security-insights-schema-1.0.0.yaml

This PR should solve https://github.com/ossf/security-insights-spec/issues/20. Now, `package-url` supports the PURL. `ecosystem` and `package-name` are still optional but supported, just in case maintainers want to publish an artifact on an ad-hoc server (e.g. `https://example.com/my-tool-latest.exe`).

Add support for PURLs

---

docs/versioning-policy.md

This PR should introduce a Versioning Policy for the Security Insights specification. This PR should solve https://github.com/ossf/security-insights-spec/issues/31.

Versioning policy

---

examples/security-insights-sample.yml
security-insights-schema-1.0.0.yaml

This addresses #25 
Previously the value `sbom-name` was used to specify the format of the SBOM (CycloneDX or SPDX). This PR changes that value to `sbom-format` to increase clarity for users.

Changed 'sbom-name' value to 'sbom-format'

---

examples/security-insights-sample.yml
security-insights-schema-1.0.0.yaml

This addresses #30 
The following changes have been made to the `security-artifacts` schema:
- Added object `self-assessment` ➕ 
- Added list object `other-artifacts` which takes arbitrary entries ➕ 
- Removed requirement for `threat-model` ❗

Security Artifacts Schema Change

---

examples/security-insights-minimal-sample.yml
examples/security-insights-sample.yml
security-insights-schema-1.0.0.yaml

This PR should solve https://github.com/ossf/security-insights-spec/issues/28.
+ `dependencies-lifecycle` 
+ `env-dependencies-policy`
(I changed the suggested names but have no strong opinion, I have tried to reuse terms already used in security standards and certifications)
+ `sca` in `tool-type`
Fixed an example, and removed some requirements.

Extend dependencies schema

---

LICENSE.md

Added LICENSE.md to cover spec and code

---

CONTRIBUTING.md
README.md
docs/user-story.md
docs/versioning-policy.md
specification.md

This PR renames "Identifying Security Threats" to "Metrics & Metadata" in the various docs in this repo.

Doc: Fix WG name

---

SECURITY-INSIGHTS.yml
examples/security-insights-minimal-sample.yml
examples/security-insights-sample.yml
security-insights-schema.yaml
specification.md

Replace `core-maintainers` with `core-team`

---

.github/ISSUE_TEMPLATES/siep.yml
GOVERNANCE.md
MAINTAINERS.md

Created this with a large draw from the OpenVEX community governance docs.
The goal is to get a few more people added as soon as possible so that we can refine the spec alongside the Security Baseline development effort.
Honestly I'm not sure who we should list as Maintainers at this time... which is both a reason that we need this PR and a complexity to getting it merged.
Closes https://github.com/ossf/security-insights-spec/issues/85

Governance Docs

---

specification.md

Fix a typo in most of the URLs; "specification" was missing a "t".
This will make it possible to navigate from specification.md to the various parts.

Fix typo in specification.md ("specificaion")

---

schema.cue
specification-details/aliases.md
specification-details/project.md
specification-details/repository.md
template-minimum.yml

This pull request includes several changes to the `schema.cue` file and documentation files to improve clarity and flexibility in the project and repository configurations. The most important changes are grouped by theme below.
* [`schema.cue`](diffhunk://#diff-fdc23bbcbafda7a99dda5a1b79a812ea24ca20bc29edb48a501a0ffd09b4f13cL56-R58): Made `homepage`, `roadmap`, and `funding` fields optional in the `project` object.
* [`schema.cue`](diffhunk://#diff-fdc23bbcbafda7a99dda5a1b79a812ea24ca20bc29edb48a501a0ffd09b4f13cR92-R97): Added `url` field and made `bug-fixes-only` and `no-third-party-packages` fields optional in the `repository` object.
* [`specification-details/project.md`](diffhunk://#diff-5df7f4a7f9496cc2af9552af0b4f6b52523c2b912f585d73a1302f3dd12104b9L5-R28): Updated documentation to …

fix: Improved clarity around required values

---

docs/MAINTAINERS.md

Following his support of the recent v2 redesign, and in order to bring the maintainer count into a healthy state, I'd like to promote @jmeridth to maintainer status on this repo.

chore: Add jmeridth as maintainer

---

.github/ISSUE_TEMPLATE/siep.yml

I noticed it was invalid when attempting to create a new SIEP issue using the template. The Github issue form shows a visible error and running yamllint against it confirms the issue.

Make the SIEP template valid YAML syntax

---

.github/ISSUE_TEMPLATE/siep.yml

Errors you see when you currently look at the `siep` ISSUE_TEMPLATE [file](https://github.com/ossf/security-insights-spec/blob/main/.github/ISSUE_TEMPLATE/siep.yml)

fix: siep issue template formatting

---

schema.cue
specification/project.md

This PR constrains how "open" the `administrators` and `repositories` list types are defined in the schema.
With their previous definitions, the following project was valid according to the schema:
```yaml
project:
name: example
administrators: []
repositories: []
vulnerability-reporting:
reports-accepted: true
bug-bounty-available: true
```
Given that the `template-minimum.yml` already illustrates this constraint and it makes logical sense, it is included in the cue schema and the Markdown docs for Project are updated to note the required list size of 1 for each list.

Further clarify/constrain the cue schema for Project

---

schema.cue
specification/repository.md

This PR constrains how "open" the list types:
- `core-team`
- `security.tools.rulesets`
- `release.distribution-points`
are within the schema.
With the previous definitions, the following
repository was valid according to the schema:
```yaml
repository:
url: https://my.vcs/foobar/foo
status: active
accepts-change-request: true
accepts-automated-change-request: true
core-team: []
license:
url: https://foo.bar/LICENSE
expression: MIT
security:
assessments:
self:
comment: |
Self assessment has not yet been completed.
tools:
name: example
type: SCA
rulesets: []
integration:
adhoc: true
ci: true
release: true
release:
automated-pipeline: true
distribution-points: []
```
With these changes, these list types now require that each list have at least a single item present

Further clarify/constrain the cue schema for Repository

---

schema.cue
specification/aliases.md
specification/header.md

This change modifies the cue schema to clearly set the expectation that the header's schema version be >= 1.0.0

Constrain the schema version in the header more clearly

---

.github/security-insights.yml
schema.cue
specification/project.md
template-full.yml

Part of #106
This pull request introduces the concept of a "steward" to the project schema and documentation. The most important changes include updates to the schema definition, documentation, and example templates to incorporate the new `steward` field.
Schema and Documentation Updates:
* [`schema.cue`](diffhunk://#diff-fdc23bbcbafda7a99dda5a1b79a812ea24ca20bc29edb48a501a0ffd09b4f13cR60): Added the optional `steward` field to the project schema.
* [`specification/project.md`](diffhunk://#diff-72b3459292b560ecf16b2f36cf48c01eaccd614e1384f67bdf95742f2d3d5f70R22): Updated the project specification to include the `steward` field, describing its type and purpose. [[1]](diffhunk://#diff-72b3459292b560ecf16b2f36cf48c01eaccd614e1384f67bdf95742f2d3d5f70R22) …

SIEP-106 changes and related content updates

---

schema.cue
specification/project.md
template-full.yml

This implements the design proposed in and closes https://github.com/ossf/security-insights-spec/issues/112
Once these changes land, here is how I imagine the field could be adopted by 2 projects that have previously adopted `security-insights.yml`
[Cilium project](https://github.com/cilium/cilium/blob/main/SECURITY-INSIGHTS.yml)
```yaml
project:
name: Cilium
homepage: https://cilium.io
roadmap: https://docs.cilium.io/en/stable/community/roadmap/
documentation:
quickstart-guide: https://docs.cilium.io/en/stable/#getting-started
detailed-guide: https://docs.cilium.io/en/stable/
code-of-conduct: https://github.com/cilium/cilium/tree/main?tab=coc-ov-file#readme
release-process: https://docs.cilium.io/en/stable/contributing/release/
support-policy: …
```

Adding project.documentation.support-policy to schema

---

.github/security-insights.yml
.github/workflows/ci.yml

This PR corrects the data type of `project.steward` and fixes a spelling error in `repository.release.automated-pipeline`
To prevent further such problems escaping our notice, the CI workflow has been updated to validate `.github/security-insights.yml` against the schema.

fix: correct errors in file preventing schema validation

---

README.md
template-full.yml
template-multi-repository-project-reuse.yml
template-multi-repository-project.yml

This change updates `README.md` to provide greater clarity to projects adopting insights and polishes some existing guidance that was inaccurate/out-of-date.
The new example files provided extend the guidance in the README and are referred to within that guidance.
This closes https://github.com/ossf/security-insights-spec/issues/126
This updates https://github.com/ossf/security-baseline/issues/257

docs: add adoption guidance docs and example files

---

.github/workflows/ci.yml
.gitignore
Makefile
docs/versioning-policy.md
schema.cue

This PR adds `make cuegen` which when run will produce output like `  >  Generating types from cue schema ...` and the file `cue_types_gen.go`
Additional tasks: `make lintcue` and `make lintyml` are added to ensure that contributors and CI are able to run the same linting processes easily inside and outside of GitHub Actions.

feat: support `cue exp gengotypes`

---

schema.cue

This change is based on feedback from the cuelang
maintainers on the issue I filed. They kindly
pointed me in this direction.
I tested this change by running `make cuegen` and
observing that the resultant `cue_types_gen.go`
begins with:
```go
// Code generated by "cue exp gengotypes"; DO NOT EDIT.
package si
```
whereas previously it would have been:
```go
// Code generated by "cue exp gengotypes"; DO NOT EDIT.
package security_insights_spec

fix: move @go package annotation in schema

---

README.md
schema.cue
specification/header.md
template-multi-repository-project-reuse.yml

These changes are being made after finding examples in the wild that provide values like `https://github.com/ossf/security-insights-spec/blob/main/.github/security-insights.yml` that are unable to be easily consumed by the code in `ossf/si-tooling`
This change relates to the changes in:
- [fix: specific project-si-source URL that provides raw access to the parent SI file](https://github.com/ossf/si-tooling/pull/27)
- ["example" test demonstrating the issue](https://github.com/ossf/si-tooling/pull/26/files#diff-2c7a40d9b54300b2087ef12ec04ebd8ae5be37e4eb341e57cea2e7f9f1bfe5caR8)

docs: improve docs on `header.project-si-source`

---

Makefile
schema.cue

This change refactors some embedded types within existing definitions into definitions themselves.
This provides a pathway to much better go types being generated by `make cuegen` and solving some of the pain observed in https://github.com/revanite-io/pvtr-github-repo/blob/main/evaluation_plans/reusable_steps/evaluations_test.go#L21
This results in the following generated go types:
```go
// Code generated by "cue exp gengotypes"; DO NOT EDIT.
package si
// URL is a TLS URL
type URL string
// Email is a valid email address
type Email string
// Date is a date in the format YYYY-MM-DD
type Date string
// SchemaVersion is a version string in the format X.Y.Z
type SchemaVersion string
// Assessment represents the results of a security assessment, including comments, evidence, and date.
type …
```

fix: add cue definitions for embedded types

---

LICENSE

The license view in GitHub currently renders in such a way that the link to the license is broken.
This change aims to correct that issue.

chore: bare link in LICENSE
